output file:
processed_cleanlabfind_label_issues120.json
function:
find_label_issues
Error Cases:

Pass or Failed: 1

Related Failed Test Cases:
set()

All Test Cases On Generated code:
============================= test session starts ==============================
platform linux -- Python 3.11.10, pytest-8.3.4, pluggy-1.5.0 -- /local/data0/moved_data/publishablew/cleanlab/cleanlab/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/publishablew/cleanlab/cleanlab
configfile: pyproject.toml
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
___________ ERROR collecting tests/test_multilabel_classification.py ___________
ImportError while importing test module '/local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_multilabel_classification.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
../publishablew/cleanlab/cleanlab/tests/test_multilabel_classification.py:24: in <module>
    from hypothesis import given, settings
E   ModuleNotFoundError: No module named 'hypothesis'
=========================== short test summary info ============================
ERROR ../publishablew/cleanlab/cleanlab/tests/test_multilabel_classification.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.64s ===============================


Final Test Result:
============================= test session starts ==============================
platform linux -- Python 3.11.10, pytest-8.3.4, pluggy-1.5.0 -- /local/data0/moved_data/publishablew/cleanlab/cleanlab/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/publishablew/cleanlab/cleanlab
configfile: pyproject.toml
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
___________ ERROR collecting tests/test_multilabel_classification.py ___________
ImportError while importing test module '/local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_multilabel_classification.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
../publishablew/cleanlab/cleanlab/tests/test_multilabel_classification.py:24: in <module>
    from hypothesis import given, settings
E   ModuleNotFoundError: No module named 'hypothesis'
=========================== short test summary info ============================
ERROR ../publishablew/cleanlab/cleanlab/tests/test_multilabel_classification.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.58s ===============================


Initial Result:
============================= test session starts ==============================
platform linux -- Python 3.11.10, pytest-8.3.4, pluggy-1.5.0 -- /local/data0/moved_data/publishablew/cleanlab/cleanlab/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/publishablew/cleanlab/cleanlab
configfile: pyproject.toml
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
___________ ERROR collecting tests/test_multilabel_classification.py ___________
ImportError while importing test module '/local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_multilabel_classification.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
../publishablew/cleanlab/cleanlab/tests/test_multilabel_classification.py:24: in <module>
    from hypothesis import given, settings
E   ModuleNotFoundError: No module named 'hypothesis'
=========================== short test summary info ============================
ERROR ../publishablew/cleanlab/cleanlab/tests/test_multilabel_classification.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.66s ===============================
