output file:
processed_pytorch3dso3_rotation_angle330.json
function:
so3_rotation_angle
Error Cases:

Pass or Failed: 1

Related Failed Test Cases:
set()

All Test Cases On Generated code:
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-8.3.3, pluggy-1.5.0 -- /local/data0/moved_data/pytorch3d/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/pytorch3d
collecting ... collected 12 items

../pytorch3d/tests/test_so3.py::TestSO3::test_bad_so3_input_value_err PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_cross PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_determinant PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_scriptable PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_cos_angle PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_cos_bound PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_cos_relative_angle PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_exp_singularity PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_exp_to_log_to_exp PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_log_singularity PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_log_to_exp_to_log PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_log_to_exp_to_log_to_exp PASSED

============================== 12 passed in 1.56s ==============================


Final Test Result:
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-8.3.3, pluggy-1.5.0 -- /local/data0/moved_data/pytorch3d/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/pytorch3d
collecting ... collected 12 items

../pytorch3d/tests/test_so3.py::TestSO3::test_bad_so3_input_value_err PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_cross PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_determinant PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_scriptable PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_cos_angle PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_cos_bound PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_cos_relative_angle PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_exp_singularity PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_exp_to_log_to_exp PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_log_singularity PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_log_to_exp_to_log PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_log_to_exp_to_log_to_exp PASSED

============================== 12 passed in 1.48s ==============================


Initial Result:
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-8.3.3, pluggy-1.5.0 -- /local/data0/moved_data/pytorch3d/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/pytorch3d
collecting ... collected 12 items

../pytorch3d/tests/test_so3.py::TestSO3::test_bad_so3_input_value_err PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_cross PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_determinant PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_scriptable PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_cos_angle PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_cos_bound PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_cos_relative_angle PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_exp_singularity PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_exp_to_log_to_exp PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_log_singularity PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_log_to_exp_to_log PASSED
../pytorch3d/tests/test_so3.py::TestSO3::test_so3_log_to_exp_to_log_to_exp PASSED

============================== 12 passed in 2.03s ==============================
